# Generated by Django 6.0.6 on 2026-07-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espn_id', models.CharField(max_length=100, unique=True)),
                ('round_name', models.CharField(max_length=50)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('went_to_extra_time', models.BooleanField(default=False)),
                ('home_penalties', models.IntegerField(blank=True, null=True)),
                ('away_penalties', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
