# Generated by Django 6.0.6 on 2026-07-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='minute',
            field=models.CharField(default="0'", max_length=20),
        ),
    ]
