# Generated by Django 6.0.6 on 2026-07-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='notified_clutch',
            field=models.BooleanField(default=False),
        ),
    ]
